#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
- name: Install httpd and firewalld packages
  ansible.builtin.dnf:
    name: 
      - httpd
      - firewalld
    state: present

- name: Start and enable httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Start and enable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
    
- name: Permanently enable httpd service in firewall
  ansible.posix.firewalld:  
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: Deploy index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd service
