#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
- name: Install httpd
  ansible.builtin.dnf:
    name: 
      - httpd
      - firewalld
    state: present

- name: Start and enable httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Start and enable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Permanently enable httpd service in firewalld
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes

- name: Deploy index.html
  ansible.builtin.copy:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd service