---
- name: Configure cron jobs for user 'natasha'
  hosts: all
  become: true
  tasks:
  - name: Creates a cron job
    ansible.builtin.cron:
      name: "EX254 logger job"
      minute: "*/2"
      user: natasha
      job: 'logger "EX254 in progress"'
      state: present
