---
- name: Configure issue file
  hosts: all
  become: true
  
  tasks:

    - name: Set Development message
      ansible.builtin.copy:
        content: "Development"
        dest: /etc/issue
      when: inventory_hostname in groups['dev']

    - name: Set Test message
      ansible.builtin.copy:
        content: "Test"
        dest: /etc/issue
      when: inventory_hostname in groups['test']

    - name: Set Production message
      ansible.builtin.copy:
        content: "Production"
        dest: /etc/issue
      when: inventory_hostname in groups['prod']
