---
- name: Configure issue file
  hosts: all
  become: true
  
  tasks:

    - name: Set Development message
      ansible.builtin.copy:
        content: "Development\n"
        dest: /etc/issue
        mode: '0644'
      when: "'dev' in group_names"

    - name: Set Test message
      ansible.builtin.copy:
        content: "Test\n"
        dest: /etc/issue
        mode: '0644'
      when: "'test' in group_names"

    - name: Set Production message
      ansible.builtin.copy:
        content: "Production\n"
        dest: /etc/issue
        mode: '0644'
      when: "'prod' in group_names"
