---
- name: Create logical volume
  hosts: all
  become: true

  tasks:

    - name: Check if research volume group exists
      ansible.builtin.command:
        cmd: vgs research
      register: vg_check
      changed_when: false
      failed_when: false

    - name: Display message if VG does not exist
      ansible.builtin.debug:
        msg: "vg not found"
      when: vg_check.rc != 0

    - name: Create 1500M logical volume
      block:

        - name: Create data LV of 1500M
          community.general.lvol:
            vg: research
            lv: data
            size: 1500M
            state: present

      rescue:

        - name: Display insufficient VG message
          ansible.builtin.debug:
            msg: "Insufficient size of vg"

        - name: Create data LV of 800M
          community.general.lvol:
            vg: research
            lv: data
            size: 800M
            state: present

      when: vg_check.rc == 0

    - name: Create ext4 filesystem on data LV
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data
      when: vg_check.rc == 0
      