---
- name: Manage packages on all nodes
  hosts: dev, test, prod
  become: true

  tasks:

  - name: Install php and maria db packages
    ansible.builtin.dnf:
      name:
        - php
        - mariadb
      state: present

  - name: Install RPM Development Tools package in dev group
    ansible.builtin.dnf:
      name: "@RPM Development Tools"
      state: present
    when: inventory_hostname in groups['dev']

  - name: Update all packages in dev group
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: inventory_hostname in groups['dev']