---
- name: Create developer and manager users
  hosts: all
  become: true

  vars_files:
    - /home/desktop/git/ansible_playbook/user_list.yml
    - /home/desktop/git/ansible_playbook/locker.yml

  tasks:
    # Create devops group
    - name: Create devops group
      ansible.builtin.group:
        name: devops
        state: present
      when:
        - "'dev' in group_names or 'test' in group_names"

    # Create opsmgr group
    - name: Create opsmgr group
      ansible.builtin.group:
        name: opsmgr
        state: present
      when:
        - "'prod' in group_names"

    # Create developer users
    - name: Create developer users
      ansible.builtin.user:
        name: "{{ item.username }}" #as per user_list.yml
        uid: "{{ item.uid }}" #as per user_list.yml
        groups: devops
        append: true
        password: "{{ pw_developer | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"
      when:
        - item.job == "developer"
        - "'dev' in group_names or 'test' in group_names"

    # Create manager users
    - name: Create manager users
      ansible.builtin.user:
        name: "{{ item.username }}" #as per user_list.yml
        uid: "{{ item.uid }}" #as per user_list.yml
        groups: opsmgr
        append: true
        password: "{{ pw_manager | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"
      when:
        - item.job == "manager"
        - "'prod' in group_names"
