---
- name: Cleanly remove LVM storage components
  hosts: all
  become: true

  tasks:
    - name: Delete logical volume data
      community.general.lvol:
        vg: research
        lv: data
        state: absent
        force: true

    - name: Delete research volume group
      community.general.lvg:
        vg: research
        state: absent

