---
- name: Configure web content
  hosts: dev
  become: true

  tasks:

  - ansible.builtin.file:
      path: /webdev
      state: directory
      mode: '2775'
      group: apache
      setype: httpd_sys_content_t

  - ansible.builtin.file:
      src: /webdev
      dest: /var/www/html/webdev
      state: link
      setype: httpd_sys_content_t

  - ansible.builtin.copy:
      content: "Development"
      dest: /webdev/index.html
      setype: httpd_sys_content_t

  - ansible.posix.firewalld:
      service: http
      state: enabled
      immediate: true
      permanent: true
