---
- name: Configure DNF repositories on all managed nodes
  hosts: all
  become: yes

  tasks:

  - name: Configure EX294_BASE repository
    ansible.builtin.yum_repository:
      name: EX294_BASE
      description: EX294 Base Repository software packages
      baseurl: http://192.168.29.120/BaseOS/
      gpgcheck: yes
      gpgkey: http://192.168.29.120/rhel-iso/RPM-GPG-KEY-redhat-release
      enabled: yes

  - name: Configure EX294_APPSTREAM repository
    ansible.builtin.yum_repository:
      name: EX294_APPSTREAM
      description: EX294 AppStream Repository software packages
      baseurl: http://192.168.29.120/AppStream/
      gpgcheck: yes
      gpgkey: http://192.168.29.120/rhel-iso/RPM-GPG-KEY-redhat-release
      enabled: yes